export const SET_USER = "SET_USER";

export const FETCH_FLIGHT = "FETCH_FLIGHT";
export const CREATE_FLIGHT = "CREATE_FLIGHT";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";

export const FETCH_AIRLINE = "FETCH_AIRLINE";


export const SEARCH_FLIGHT = "SEARCH_FLIGHT";

export const FETCH_DESTINATIONS = "FETCH_DESTINATIONS";
