
export const SET_USER = 'SET_USER';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const FETCH_FLIGHT = 'FETCH_FLIGHT';
export const CREATE_FLIGHT = 'CREATE_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const SEARCH_FLIGHT = 'SEARCH_FLIGHT';

export const FETCH_DESTINATIONS = 'FETCH_DESTINATIONS';