//USER
export const SET_USER = "SET_USER";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

//FLIGHTS
export const FETCH_FLIGHTS = "FETCH_FLIGHTS";
export const CREATE_FLIGHT = "CREATE_FLIGHT";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";
export const SEARCH_FLIGHT = "SEARCH_FLIGHT";

//DESTINATIONS
export const FETCH_DESTINATIONS = "FETCH_DESTINATIONS";

//AIRLINES
export const FETCH_AIRLINES = "FETCH_AIRLINES";
